apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "agents.labels" . | nindent 4 }}
    {{- include "agents.api.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "agents.api.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
      protocol: TCP
