{{- if gt (int .Values.api.replicaCount) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cerrado-api-pdb
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "cerrado.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "cerrado.api.selectorLabels" . | nindent 6 }}
{{- end }}
