{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    pod-security.kubernetes.io/enforce: baseline
    {{- include "cerrado.labels" . | nindent 4 }}
{{- end }}
