apiVersion: v1
kind: Service
metadata:
  name: cerrado-web
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "cerrado.labels" . | nindent 4 }}
    {{- include "cerrado.web.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "cerrado.web.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: {{ .Values.web.port }}
      protocol: TCP
